include: package:solid_lints/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore

custom_lint:
  rules:
    - avoid_returning_widgets: false
    - prefer_match_file_name: false
