targets:
  $default:
    builders:
      functional_widget:
        enabled: true

builders:
  functional_widget:
    import: 'package:functional_widget/builder.dart'
    builder_factories: ['functionalWidget']
    build_extensions: { '.dart': ['.functional_widget.g.part'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
  auto_route_generator:
    import: "package:auto_route_generator/builder.dart"
    runs_before: [
      "functional_widget",
      "auto_route_generator:auto_router_generator",
      "auto_route_generator:auto_router_module_generator",
    ]
    builder_factories: ["autoRouteBuilder"]
    build_extensions: { ".dart": [".route.json"] }
    auto_apply: dependents
    build_to: cache

  auto_router_generator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: ["autoRouterBuilder"]
    build_extensions: { ".dart": [ ".gr.dart" ] }
    auto_apply: dependents
    build_to: source
  auto_router_module_generator:
    import: "package:auto_route_generator/builder.dart"
    runs_before: [
      "functional_widget",
      "auto_route_generator:auto_router_generator",
      ]
    builder_factories: ["autoRouterModuleBuilder"]
    build_extensions: { ".dart": [ ".gm.dart" ] }
    auto_apply: dependents
    build_to: source
