name: me
description: "Me."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: 9.2.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  functional_widget_annotation: ^0.10.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  auto_route_generator: 9.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  functional_widget: ^0.10.2
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  solid_lints: ^0.2.3

flutter:
  uses-material-design: true
