name: me
description: "Me."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: 9.2.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  functional_widget_annotation: ^0.10.0

dev_dependencies:
  auto_route_generator: 9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  functional_widget: ^0.10.2
  solid_lints: ^0.2.3

flutter:
  uses-material-design: true
