name: me
description: "Me."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5
  functional_widget_annotation: ^0.10.0

dev_dependencies:
  functional_widget: ^0.10.2
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  solid_lints: ^0.2.3

flutter:
  uses-material-design: true
