name: lints

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - run: flutter pub get

      - run: dart run build_runner build

      - uses: zgosalvez/github-actions-analyze-dart@v3.0.6
        with:
          fail-on-infos: true 
          fail-on-warnings: true

      - run: dart run custom_lint
